version = 1
SPDX-PackageName = "certorder"
SPDX-PackageSupplier = "Comcast Cable Communications Management, LLC"
SPDX-PackageDownloadLocation = "https://github.com/xmidt-org/certorder"

[[annotations]]
path = ["go.mod", "go.sum"]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"
