# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

permissions:
  pull-requests: write
  contents: write

on:
  pull_request_target

jobs:
  dependabot:
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@79ef455d3e925fe97bb0dbf2dec7af4f4008ee0b # v4.11.6
    secrets: inherit
