# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

permissions:
  pull-requests: write
  contents: write

on:
  pull_request_target

jobs:
  dependabot:
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@587eb1b9f75e59e208ee17ae3890d16757b006d9 # v4.11.3
    secrets: inherit
