# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  project:
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@22a6e87c727e4ee31658bfa175e4124549703e11 # v4.9.46
    secrets: inherit
