# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  project:
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@bfcee2e5632b9b052e8176a73a9523f226ba7ef4 # v4.12.15
    secrets: inherit
