# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  project:
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@bf189b2c40e583cdaee276d666b69d3f47598ec7 # v4.12.0
    secrets: inherit
